### ISSUE TITLE
Let me climb stairs

### ISSUE THREAD

**Issue by cvan** [mattbasta/superior-marco-cousins#10]
![screenshot 2014-09-23 10 23 33](https://cloud.githubusercontent.com/assets/203725/4376525/4b93c636-4346-11e4-9781-bd9716e5c001.png)

**Comment by mattbasta** [comment]
is done

**Comment by cvan** [comment]
I can sort of climb up stairs now. But I can't get to the top. I just fall. And I can't climb down stairs.

**Comment by mattbasta** [comment]
I only have mechanics for going up. Making it work for going down really complicates the hit  testing. I experimented with it a bit and making the ladders sticky causes quite a lot of dissonance. Even slowing the player's descent like in Minecraft didn't work very well. 

The only change I'd like to make is to have the player get slowly nudged to the center of the ladder they're climbing. That way you can climb a ladder through a one wide gap or past a floor without hitting your head.
