### ISSUE TITLE
Cannot enter names containing the letter P

### ISSUE THREAD

**Issue by cvan** [mattbasta/superior-marco-cousins#18]
1. Die
2. Enter your name ("Poop") when it says "Enter your name:"
3. Notice the game pauses (sorry, **hesitates**) 

![](https://cloud.githubusercontent.com/assets/203725/4467923/0bba1a0a-48f6-11e4-8bbb-110ed09b426a.png)

**Comment by mattbasta** [comment]
resolved on dart branch
