### ISSUE TITLE
Weird characters when entering my name

### ISSUE THREAD

**Issue by cvan** [mattbasta/superior-marco-cousins#19]
1. Die
2. Enter your name (`<script>`) when it says "Enter your name:"
3. Notice `¼` and `¾` characters appears instead of `<` and `>`, respectively

![](https://cloud.githubusercontent.com/assets/203725/4467945/6efc3c38-48f6-11e4-900e-d32c4f1262d3.png)

**Comment by mattbasta** [comment]
rolled into #23

**Comment by cvan** [comment]
still happens

![screenshot 2014-10-07 19 40 30](https://cloud.githubusercontent.com/assets/203725/4553180/c31342aa-4e94-11e4-865b-a8754ae9ba64.png)

**Comment by cvan** [comment]
oh. I see #23.
