### ISSUE TITLE
`[` character appears in my name upon window refocus

### ISSUE THREAD

**Issue by cvan** [mattbasta/superior-marco-cousins#21]
1. Die
2. Start entering your name (`<script>`) when it says "Enter your name:"
3. Open a different browser window
4. Return to SMC
5. Notice `[` character appears in my name:
   ![](https://cloud.githubusercontent.com/assets/203725/4467980/f23e27dc-48f6-11e4-804f-337e029def25.png)

**Comment by mattbasta** [comment]
rolled into #23
